# Generated by Django 3.1.5 on 2021-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_inventory', '0005_auto_20210202_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(choices=[('SILVER 4', 'SILVER 4'), ('SILVER5', 'SILVER 5'), ('SILVER 6', 'SILVER 6'), ('WHITE 6', 'WHITE 6'), ('PRESBY', 'PRESBY'), ('PCAM3', 'PCAM3'), ('PCAM4', 'PCAM4'), ('GATES5', 'GATES 5'), ('GROUND FOUNDERS 013', 'GROUND FOUNDERS 013'), ('GROUN', 'GROUND FOUNDER 079'), ('STEMMLER HALL', 'STEMMLER HALL'), ('RAV 5 COURTYARD', 'RAV 5 COURTYARD'), ('DULLES 2', 'DULLES 2'), ('DULLES 2 COURT', 'DULLES 2 COURT'), ('SILVER5', 'SILVER5'), ('1500 MARKET ST', '1500 MARKET ST'), ('SPE1', 'SPE1'), ('SPE14', 'SPE14'), ('SPE10', 'SPE10'), ('MALONEY 5', 'MALONEY 5'), ('MALONEY 4', 'MALONEY 4'), ('OTHER', 'OTHER')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS 10', 'WINDOWS 10'), ('WINDOWS 7', 'WINDOWS 7')], default='WINDOWS 10', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
